[2022-12-26T13:58:35.977+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:36.037+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:36.039+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:36.040+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-26T13:58:36.040+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:36.118+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_RUB_USD> on 2022-06-25 08:15:00+00:00
[2022-12-26T13:58:36.134+0000] {standard_task_runner.py:54} INFO - Started process 8370 to run task
[2022-12-26T13:58:36.163+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_RUB_USD', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '4257', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmp1by7e8tj']
[2022-12-26T13:58:36.184+0000] {standard_task_runner.py:83} INFO - Job 4257: Subtask insert_rate_RUB_USD
[2022-12-26T13:58:36.187+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2022-12-26T13:58:36.554+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.555+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.791+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2022-12-26T13:58:36.911+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-12-26T13:58:37.065+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_RUB_USD
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2022-12-26T13:58:37.091+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-26T13:58:37.097+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('RUB', 'USD', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2022-12-26T13:58:37.104+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('RUB', 'USD', None, '2022-06-25')
                              ^

[2022-12-26T13:58:37.126+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_RUB_USD, execution_date=20220625T081500, start_date=20221226T135835, end_date=20221226T135837
[2022-12-26T13:58:37.164+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4257 for task insert_rate_RUB_USD (column "none" does not exist
LINE 3: VALUES ('RUB', 'USD', None, '2022-06-25')
                              ^
; 8370)
[2022-12-26T13:58:37.266+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-26T13:58:37.297+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-01T14:42:42.591+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.646+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.647+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.647+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-01T14:42:42.648+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.692+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_RUB_USD> on 2022-06-25 08:15:00+00:00
[2023-01-01T14:42:42.702+0000] {standard_task_runner.py:54} INFO - Started process 8991 to run task
[2023-01-01T14:42:42.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_RUB_USD', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '10233', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmpmrixleox']
[2023-01-01T14:42:42.739+0000] {standard_task_runner.py:83} INFO - Job 10233: Subtask insert_rate_RUB_USD
[2023-01-01T14:42:42.743+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2023-01-01T14:42:43.081+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.085+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.245+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_RUB_USD scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2023-01-01T14:42:43.352+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-01T14:42:43.481+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_RUB_USD
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2023-01-01T14:42:43.500+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-01-01T14:42:43.519+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('RUB', 'USD', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2023-01-01T14:42:43.523+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('RUB', 'USD', None, '2022-06-25')
                              ^

[2023-01-01T14:42:43.539+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_RUB_USD, execution_date=20220625T081500, start_date=20230101T144242, end_date=20230101T144243
[2023-01-01T14:42:43.579+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10233 for task insert_rate_RUB_USD (column "none" does not exist
LINE 3: VALUES ('RUB', 'USD', None, '2022-06-25')
                              ^
; 8991)
[2023-01-01T14:42:43.621+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-01T14:42:43.649+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
